// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh_mZ5r6MkSt58Fpwg3gT5eFMaZFUvUl0',
    appId: '1:516710649340:web:2a8ead0804148b2e267679',
    messagingSenderId: '516710649340',
    projectId: 'expense-tracker-9e3d7',
    authDomain: 'expense-tracker-9e3d7.firebaseapp.com',
    storageBucket: 'expense-tracker-9e3d7.firebasestorage.app',
    measurementId: 'G-SNR47LS3NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG844ZY04jLlGZbocU0P5CpJz_XU2FCw4',
    appId: '1:516710649340:android:b891352f7fc9d749267679',
    messagingSenderId: '516710649340',
    projectId: 'expense-tracker-9e3d7',
    storageBucket: 'expense-tracker-9e3d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc_6gxP5wBBEejHV1NJMXljrjncfbCbe4',
    appId: '1:516710649340:ios:b5a30bc5579e83d0267679',
    messagingSenderId: '516710649340',
    projectId: 'expense-tracker-9e3d7',
    storageBucket: 'expense-tracker-9e3d7.firebasestorage.app',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc_6gxP5wBBEejHV1NJMXljrjncfbCbe4',
    appId: '1:516710649340:ios:b5a30bc5579e83d0267679',
    messagingSenderId: '516710649340',
    projectId: 'expense-tracker-9e3d7',
    storageBucket: 'expense-tracker-9e3d7.firebasestorage.app',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh_mZ5r6MkSt58Fpwg3gT5eFMaZFUvUl0',
    appId: '1:516710649340:web:137358fddf14a069267679',
    messagingSenderId: '516710649340',
    projectId: 'expense-tracker-9e3d7',
    authDomain: 'expense-tracker-9e3d7.firebaseapp.com',
    storageBucket: 'expense-tracker-9e3d7.firebasestorage.app',
    measurementId: 'G-7N2ZZ0PK7M',
  );
}
